# Generated by Django 4.1 on 2022-08-14 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_title', models.CharField(max_length=20)),
                ('room_interest', models.CharField(max_length=20)),
                ('room_place', models.CharField(max_length=50)),
                ('room_date', models.DateField()),
                ('room_time', models.TimeField()),
                ('room_headcount', models.IntegerField(default=1)),
                ('room_status', models.IntegerField(default=0)),
                ('room_created_time', models.DateTimeField(auto_now_add=True)),
                ('user_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='room.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apply_time'],
            },
        ),
    ]
