# Generated by Django 4.1 on 2022-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_time',
            field=models.TimeField(),
        ),
    ]
