# Generated by Django 4.1 on 2022-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_room_date_alter_room_room_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
