# Generated by Django 4.1 on 2022-09-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_user_email_remove_user_user_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_img',
            field=models.ImageField(blank=True, default='', upload_to='%Y%m%d/'),
        ),
    ]
